import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function tile(props) {
  const { nodes, materials } = useGLTF("/city.glb");
  return (
    <group {...props} scale={[0.08,.3,.08]} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SPORTINGdefLayer1_SPORTING_Material_u1_v1_0.geometry}
        material={materials.SPORTING_Material_u1_v1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SPORTINGdefLayer1_SPORTING_Material_u1_v2_0.geometry}
        material={materials.SPORTING_Material_u1_v2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SPORTINGdefLayer1_SPORTING_Material_u1_v3_0.geometry}
        material={materials.SPORTING_Material_u1_v3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SPORTINGdefLayer1_SPORTING_Material_u1_v4_0.geometry}
        material={materials.SPORTING_Material_u1_v4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SPORTINGdefLayer1_SPORTING_Material_u1_v5_0.geometry}
        material={materials.SPORTING_Material_u1_v5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SPORTINGdefLayer1_SPORTING_Material_u2_v1_0.geometry}
        material={materials.SPORTING_Material_u2_v1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SPORTINGdefLayer1_SPORTING_Material_u2_v2_0.geometry}
        material={materials.SPORTING_Material_u2_v2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SPORTINGdefLayer1_SPORTING_Material_u2_v3_0.geometry}
        material={materials.SPORTING_Material_u2_v3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SPORTINGdefLayer1_SPORTING_Material_u2_v4_0.geometry}
        material={materials.SPORTING_Material_u2_v4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SPORTINGdefLayer1_SPORTING_Material_u2_v5_0.geometry}
        material={materials.SPORTING_Material_u2_v5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SPORTINGdefLayer1_SPORTING_Material_u3_v1_0.geometry}
        material={materials.SPORTING_Material_u3_v1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SPORTINGdefLayer1_SPORTING_Material_u3_v2_0.geometry}
        material={materials.SPORTING_Material_u3_v2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SPORTINGdefLayer1_SPORTING_Material_u3_v3_0.geometry}
        material={materials.SPORTING_Material_u3_v3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SPORTINGdefLayer1_SPORTING_Material_u3_v4_0.geometry}
        material={materials.SPORTING_Material_u3_v4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SPORTINGdefLayer1_SPORTING_Material_u3_v5_0.geometry}
        material={materials.SPORTING_Material_u3_v5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SPORTINGdefLayer1_SPORTING_Material_u4_v1_0.geometry}
        material={materials.SPORTING_Material_u4_v1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SPORTINGdefLayer1_SPORTING_Material_u4_v2_0.geometry}
        material={materials.SPORTING_Material_u4_v2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SPORTINGdefLayer1_SPORTING_Material_u4_v3_0.geometry}
        material={materials.SPORTING_Material_u4_v3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SPORTINGdefLayer1_SPORTING_Material_u4_v4_0.geometry}
        material={materials.SPORTING_Material_u4_v4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SPORTINGdefLayer1_SPORTING_Material_u4_v5_0.geometry}
        material={materials.SPORTING_Material_u4_v5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SPORTINGdefLayer1_SPORTING_Material_u5_v1_0.geometry}
        material={materials.SPORTING_Material_u5_v1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SPORTINGdefLayer1_SPORTING_Material_u5_v2_0.geometry}
        material={materials.SPORTING_Material_u5_v2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SPORTINGdefLayer1_SPORTING_Material_u5_v3_0.geometry}
        material={materials.SPORTING_Material_u5_v3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SPORTINGdefLayer1_SPORTING_Material_u5_v4_0.geometry}
        material={materials.SPORTING_Material_u5_v4}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SPORTINGdefLayer1_SPORTING_Material_u5_v5_0.geometry}
        material={materials.SPORTING_Material_u5_v5}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SPORTINGdefLayer1_SPORTING_Material_u6_v1_0.geometry}
        material={materials.SPORTING_Material_u6_v1}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SPORTINGdefLayer1_SPORTING_Material_u6_v2_0.geometry}
        material={materials.SPORTING_Material_u6_v2}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SPORTINGdefLayer1_SPORTING_Material_u6_v3_0.geometry}
        material={materials.SPORTING_Material_u6_v3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SPORTINGdefLayer1_SPORTING_Material_u6_v4_0.geometry}
        material={materials.SPORTING_Material_u6_v4}
      />
    </group>
  );
}

useGLTF.preload("/city.glb");

export default tile;
